name: realtime-ws-notification

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./backend:/app
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8000/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    name: realtime-ws-network
    driver: bridge
